version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - cd my-app
      - npm install

  pre_build:
    commands:
      - echo Running pre-build commands...

  build:
    commands:
      - echo Running tests...
      - cd my-app
      - CI=true npm run test
      - echo Building the application...
      - npm run build

  post_build:
    commands:
      - echo Running post-build commands...
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: my-app/build
  discard-paths: yes